// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204061058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Estoque")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Catalogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Periféricos",
                            Estoque = 15,
                            Nome = "Mouse Gamer RGB",
                            Preco = 120.90m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Periféricos",
                            Estoque = 8,
                            Nome = "Teclado Mecânico Redragon",
                            Preco = 289.00m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Monitores",
                            Estoque = 5,
                            Nome = "Monitor 27'' 144hz",
                            Preco = 1499.90m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Hardware",
                            Estoque = 3,
                            Nome = "Notebook i7 16GB 512SSD",
                            Preco = 4899.90m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Headset",
                            Estoque = 10,
                            Nome = "Headset HyperX Cloud",
                            Preco = 399.90m
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Hardware",
                            Estoque = 4,
                            Nome = "Placa de Vídeo RTX 4060 8GB",
                            Preco = 2399.00m
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "Armazenamento",
                            Estoque = 12,
                            Nome = "SSD NVMe 1TB Gen4",
                            Preco = 499.90m
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "Redes",
                            Estoque = 9,
                            Nome = "Roteador Wi-Fi 6 AX1800",
                            Preco = 349.00m
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "Acessórios",
                            Estoque = 6,
                            Nome = "Cadeira Gamer Ergonômica",
                            Preco = 899.90m
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "Periféricos",
                            Estoque = 14,
                            Nome = "Webcam Full HD 1080p",
                            Preco = 189.00m
                        },
                        new
                        {
                            Id = 11,
                            Categoria = "Acessórios",
                            Estoque = 5,
                            Nome = "Mesa Gamer",
                            Preco = 1200.00m
                        },
                        new
                        {
                            Id = 12,
                            Categoria = "Hardware",
                            Estoque = 3,
                            Nome = "Computador Gamer",
                            Preco = 7200.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
